# Generated by Django 4.2 on 2024-12-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('moderator', 'Moderator')], max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingPetForAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('additional_details', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adoption_id', models.CharField(blank=True, max_length=36, unique=True)),
                ('adoption_status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetAdoptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date_time', models.DateTimeField(blank=True, null=True)),
                ('adopter_type', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family'), ('Organization', 'Organization')], max_length=20)),
                ('living_situation', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Condo', 'Condo')], max_length=20)),
                ('previous_pet_experience', models.TextField()),
                ('owns_other_pets', models.CharField(max_length=100)),
                ('facebook_profile_link', models.URLField(blank=True, null=True)),
                ('adoption_request_status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('adopted', 'Adopted'), ('pet_is_adopted', 'Pet_is_adopted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.pendingpetforadoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackUpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('living_situation', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10)),
                ('housing_type', models.CharField(choices=[('cage', 'Cage'), ('free_roaming', 'Free Roaming')], max_length=15)),
                ('behavioral_changes', models.TextField(blank=True)),
                ('health_issues', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, upload_to='track_updates_photos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_adoption_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.petadoptiontable')),
            ],
        ),
        migrations.CreateModel(
            name='PetAdoptionRequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('adopter_type', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family'), ('Organization', 'Organization')], max_length=20)),
                ('living_situation', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Condo', 'Condo')], max_length=20)),
                ('previous_pet_experience', models.TextField()),
                ('owns_other_pets', models.CharField(max_length=100)),
                ('adoption_request_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.pendingpetforadoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
