# Generated by Django 5.0.6 on 2024-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoptiontable',
            name='approval_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
