# Generated by Django 4.2 on 2024-12-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
