# Generated by Django 5.0.6 on 2024-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_petadoptiontable_approval_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoptiontable',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
