# Generated by Django 4.2 on 2024-11-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_petadoptiontable_adoption_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoptiontable',
            name='adoption_request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
