# Generated by Django 4.2 on 2024-12-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpetforadoption',
            name='adoption_id',
        ),
    ]
