# Generated by Django 4.2 on 2024-11-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_alter_petadoptiontable_adoption_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('living_situation', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10)),
                ('housing_type', models.CharField(choices=[('cage', 'Cage'), ('free_roaming', 'Free Roaming')], max_length=15)),
                ('behavioral_changes', models.TextField(blank=True)),
                ('health_issues', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, upload_to='track_updates_photos/')),
                ('pet_adoption_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.petadoptiontable')),
            ],
        ),
    ]
