# Generated by Django 4.2 on 2024-11-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0009_trackupdatetable_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackupdatetable',
            name='author',
        ),
    ]
