# Generated by Django 4.2 on 2024-11-25 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption', '0012_alter_trackupdatetable_uthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackupdatetable',
            name='uthor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
