# Generated by Django 4.2 on 2024-11-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0013_alter_trackupdatetable_uthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackupdatetable',
            old_name='uthor',
            new_name='author',
        ),
    ]
