# Generated by Django 4.2 on 2024-12-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0016_trackupdatetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoptiontable',
            name='facebook_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
